server:
  port: 80

spring:
  application:
    name: phonebook

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      username: sa
      mode: always
      password:

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: status
