server:
  port: 80

spring:
  application:
    name: phonebook

  datasource:
    url: jdbc:mysql://172.31.80.8:3306/phonebook_db
    username: root
    password: my-secret-pw
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        default_schema: phonebook_db
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5Dialect

  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.yml
    drop-first: false
    default-schema: phonebook_db
    database-change-log-table: PHONEBOOK_DBCHANGELOG
    database-change-log-lock-table: PHONEBOOK_DBCHANGELOGLOCK

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: status
